In [142]:
import pandas as pd
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader

In [143]:

# 1. Load Ratings (UserID::MovieID::Rating::Timestamp)

rating_cols = ['user_id', 'item_id', 'rating', 'timestamp']
ratings = pd.read_csv('ml-1m/ratings.dat', sep='::', names=rating_cols, 
                      engine='python', encoding='latin-1')

In [144]:
ratings['rating'].value_counts()

rating
4    348971
3    261197
5    226310
2    107557
1     56174
Name: count, dtype: int64

In [145]:
# 2. Load Users (UserID::Gender::Age::Occupation::Zip-code)

user_cols = ['user_id', 'gender', 'age', 'occupation', 'zip']
users = pd.read_csv('ml-1m/users.dat', sep='::', names=user_cols, 
                    engine='python', encoding='latin-1')

In [146]:
users

      user_id gender  age  occupation    zip
0           1      F    1          10  48067
1           2      M   56          16  70072
2           3      M   25          15  55117
3           4      M   45           7  02460
4           5      M   25          20  55455
...       ...    ...  ...         ...    ...
6035     6036      F   25          15  32603
6036     6037      F   45           1  76006
6037     6038      F   56           1  14706
6038     6039      F   45           0  01060
6039     6040      M   25           6  11106

[6040 rows x 5 columns]

In [147]:
users[users['age'] == 1] ### These are people below the age of 18, for more info about dataset -> readme

      user_id gender  age  occupation    zip
0           1      F    1          10  48067
18         19      M    1          10  48073
50         51      F    1          10  10562
74         75      F    1          10  01748
85         86      F    1          10  54467
...       ...    ...  ...         ...    ...
5843     5844      F    1          10  02131
5952     5953      M    1          10  21030
5972     5973      M    1          10  54701
5988     5989      F    1          10  74114
6005     6006      F    1           0  01036

[222 rows x 5 columns]

In [148]:
# 3. Load Movies (MovieID::Title::Genres)

movie_cols = ['item_id', 'title', 'genres']
movies = pd.read_csv('ml-1m/movies.dat', sep='::', names=movie_cols, 
                     engine='python', encoding='latin-1')

In [149]:
movies

,item_id,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

In [150]:
print(ratings.isnull().any())
print(movies.isnull().any())
print(users.isnull().any())

user_id      False
item_id      False
rating       False
timestamp    False
dtype: bool
item_id    False
title      False
genres     False
dtype: bool
user_id       False
gender        False
age           False
occupation    False
zip           False
dtype: bool

In [151]:
ratings['user_id']

0             1
1             1
2             1
3             1
4             1
           ...
1000204    6040
1000205    6040
1000206    6040
1000207    6040
1000208    6040
Name: user_id, Length: 1000209, dtype: int64

###  Drop the original 'rating' to avoid accidental star-prediction logic, we need to only consider implicit interactions

In [152]:
ratings['target'] = 1 

ratings = ratings.drop(columns=['rating'])

In [153]:
ratings['target']

0          1
1          1
2          1
3          1
4          1
          ..
1000204    1
1000205    1
1000206    1
1000207    1
1000208    1
Name: target, Length: 1000209, dtype: int64

In [154]:
users

      user_id gender  age  occupation    zip
0           1      F    1          10  48067
1           2      M   56          16  70072
2           3      M   25          15  55117
3           4      M   45           7  02460
4           5      M   25          20  55455
...       ...    ...  ...         ...    ...
6035     6036      F   25          15  32603
6036     6037      F   45           1  76006
6037     6038      F   56           1  14706
6038     6039      F   45           0  01060
6039     6040      M   25           6  11106

[6040 rows x 5 columns]

In [155]:
print((movies['item_id'].unique()))
print(ratings['user_id'].unique())

[   1    2    3 ... 3950 3951 3952]
[   1    2    3 ... 6038 6039 6040]

### Mapping of user_to_index and item_to_index so that model won't select invalid(unmapped) indices i.e empty because these are identifiers just random numbers that's why adjusting them according to index

In [156]:
# Create mapping dictionaries
user_to_idx = {user_id: i for i, user_id in enumerate(ratings['user_id'].unique())}
item_to_idx = {item_id: i for i, item_id in enumerate(movies['item_id'].unique())}


# Apply to the ratings table
ratings['user_id'] = ratings['user_id'].map(user_to_idx)
ratings['item_id'] = ratings['item_id'].map(item_to_idx)

# # Save the counts for your model initialization
num_users = len(user_to_idx)
num_items = len(item_to_idx)

In [157]:
ratings

         user_id  item_id  timestamp  target
0              0     1176  978300760       1
1              0      655  978302109       1
2              0      902  978301968       1
3              0     3339  978300275       1
4              0     2286  978824291       1
...          ...      ...        ...     ...
1000204     6039     1075  956716541       1
1000205     6039     1078  956704887       1
1000206     6039      558  956704746       1
1000207     6039     1080  956715648       1
1000208     6039     1081  956715569       1

[1000209 rows x 4 columns]

In [158]:
num_items,num_users

(3883, 6040)

In [159]:
ratings['item_id']

0          1176
1           655
2           902
3          3339
4          2286
           ...
1000204    1075
1000205    1078
1000206     558
1000207    1080
1000208    1081
Name: item_id, Length: 1000209, dtype: int64

In [160]:
ratings

         user_id  item_id  timestamp  target
0              0     1176  978300760       1
1              0      655  978302109       1
2              0      902  978301968       1
3              0     3339  978300275       1
4              0     2286  978824291       1
...          ...      ...        ...     ...
1000204     6039     1075  956716541       1
1000205     6039     1078  956704887       1
1000206     6039      558  956704746       1
1000207     6039     1080  956715648       1
1000208     6039     1081  956715569       1

[1000209 rows x 4 columns]

#### Leave-One-Out Temporal Split. A recommendation model can't look into the future. It has to predict what you will watch next based on what you had watched. Splitting by time prevents data leakage

In [161]:
# Sort by timestamp to find the latest interaction and insert it into test set 
ratings = ratings.sort_values(by=['user_id', 'timestamp'])

# Shift the last interaction for each user to the test set
test_ratings = ratings.groupby('user_id').tail(1)
train_ratings = ratings.drop(test_ratings.index)

print(f"Split complete. Training size: {len(train_ratings)}, Test size: {len(test_ratings)}")

Split complete. Training size: 994169, Test size: 6040

In [162]:
train_ratings

         user_id  item_id  timestamp  target
31             0     3117  978300019       1
22             0     1250  978300055       1
27             0     1672  978300055       1
37             0     1009  978300055       1
24             0     2271  978300103       1
...          ...      ...        ...     ...
999923      6039      229  997454398       1
1000019     6039     2848  997454429       1
999988      6039     1852  997454464       1
1000172     6039     1726  997454464       1
1000167     6039      159  997454486       1

[994169 rows x 4 columns]

In [163]:
ratings

         user_id  item_id  timestamp  target
31             0     3117  978300019       1
22             0     1250  978300055       1
27             0     1672  978300055       1
37             0     1009  978300055       1
24             0     2271  978300103       1
...          ...      ...        ...     ...
1000019     6039     2848  997454429       1
999988      6039     1852  997454464       1
1000172     6039     1726  997454464       1
1000167     6039      159  997454486       1
1000042     6039     1203  998315055       1

[1000209 rows x 4 columns]

In [164]:
train_ratings

         user_id  item_id  timestamp  target
31             0     3117  978300019       1
22             0     1250  978300055       1
27             0     1672  978300055       1
37             0     1009  978300055       1
24             0     2271  978300103       1
...          ...      ...        ...     ...
999923      6039      229  997454398       1
1000019     6039     2848  997454429       1
999988      6039     1852  997454464       1
1000172     6039     1726  997454464       1
1000167     6039      159  997454486       1

[994169 rows x 4 columns]

In [165]:
num_items # There are 6040 unique users and 3706 movies

3883

In [166]:
movies

,item_id,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

In [167]:
len(movies)

3883

#### Creating a lookup for positive and negative instances 0's and 1's. here we use negative sampling strategy of 4 : 1. So for every user we map it with for 4 random movies that they never interacted with. It's an unobserved entity from the user perspective

In [168]:
### negative sampling function is transferred to train.py

In [169]:
train_ratings[['item_id','user_id']]

         item_id  user_id
31          3117        0
22          1250        0
27          1672        0
37          1009        0
24          2271        0
...          ...      ...
999923       229     6039
1000019     2848     6039
999988      1852     6039
1000172     1726     6039
1000167      159     6039

[994169 rows x 2 columns]

In [170]:
train_ratings

         user_id  item_id  timestamp  target
31             0     3117  978300019       1
22             0     1250  978300055       1
27             0     1672  978300055       1
37             0     1009  978300055       1
24             0     2271  978300103       1
...          ...      ...        ...     ...
999923      6039      229  997454398       1
1000019     6039     2848  997454429       1
999988      6039     1852  997454464       1
1000172     6039     1726  997454464       1
1000167     6039      159  997454486       1

[994169 rows x 4 columns]

In [171]:

# Generate the data for the training loop
# train_u, train_i, train_labels = get_train_instances(train_ratings,num_items)

In [172]:
# train_u,train_i,train_labels

In [173]:
users

      user_id gender  age  occupation    zip
0           1      F    1          10  48067
1           2      M   56          16  70072
2           3      M   25          15  55117
3           4      M   45           7  02460
4           5      M   25          20  55455
...       ...    ...  ...         ...    ...
6035     6036      F   25          15  32603
6036     6037      F   45           1  76006
6037     6038      F   56           1  14706
6038     6039      F   45           0  01060
6039     6040      M   25           6  11106

[6040 rows x 5 columns]

In [174]:
users['user_id']
users['user_id'] = users['user_id'].map(user_to_idx) # mapping in user dataframe

In [175]:
users['gender'] = users['gender'].map({'M': 0, 'F': 1})
# users['gender'].value_counts()
 
# users['gender'] = users['gender'].str.strip()

In [176]:
users

      user_id  gender  age  occupation    zip
0           0       1    1          10  48067
1           1       0   56          16  70072
2           2       0   25          15  55117
3           3       0   45           7  02460
4           4       0   25          20  55455
...       ...     ...  ...         ...    ...
6035     6035       1   25          15  32603
6036     6036       1   45           1  76006
6037     6037       1   56           1  14706
6038     6038       1   45           0  01060
6039     6039       0   25           6  11106

[6040 rows x 5 columns]

In [177]:
users['gender'].value_counts()

gender
0    4331
1    1709
Name: count, dtype: int64

In [178]:
users['occupation'].value_counts()

occupation
4     759
0     711
7     679
1     528
17    502
12    388
14    302
20    281
2     267
16    241
6     236
10    195
3     173
15    144
13    142
11    129
5     112
9      92
19     72
18     70
8      17
Name: count, dtype: int64

In [179]:
users.columns

Index(['user_id', 'gender', 'age', 'occupation', 'zip'], dtype='object')

In [180]:
users['zip'].value_counts()

zip
48104    19
22903    18
94110    17
55104    17
55105    16
         ..
91330     1
58102     1
91306     1
61265     1
30066     1
Name: count, Length: 3439, dtype: int64

In [181]:
item_to_idx

{np.int64(1): 0,
 np.int64(2): 1,
 np.int64(3): 2,
 np.int64(4): 3,
 np.int64(5): 4,
 np.int64(6): 5,
 np.int64(7): 6,
 np.int64(8): 7,
 np.int64(9): 8,
 np.int64(10): 9,
 np.int64(11): 10,
 np.int64(12): 11,
 np.int64(13): 12,
 np.int64(14): 13,
 np.int64(15): 14,
 np.int64(16): 15,
 np.int64(17): 16,
 np.int64(18): 17,
 np.int64(19): 18,
 np.int64(20): 19,
 np.int64(21): 20,
 np.int64(22): 21,
 np.int64(23): 22,
 np.int64(24): 23,
 np.int64(25): 24,
 np.int64(26): 25,
 np.int64(27): 26,
 np.int64(28): 27,
 np.int64(29): 28,
 np.int64(30): 29,
 np.int64(31): 30,
 np.int64(32): 31,
 np.int64(33): 32,
 np.int64(34): 33,
 np.int64(35): 34,
 np.int64(36): 35,
 np.int64(37): 36,
 np.int64(38): 37,
 np.int64(39): 38,
 np.int64(40): 39,
 np.int64(41): 40,
 np.int64(42): 41,
 np.int64(43): 42,
 np.int64(44): 43,
 np.int64(45): 44,
 np.int64(46): 45,
 np.int64(47): 46,
 np.int64(48): 47,
 np.int64(49): 48,
 np.int64(50): 49,
 np.int64(51): 50,
 np.int64(52): 51,
 np.int64(53): 52,
 np.int64(54): 53,
 np.int64(55): 54,
 np.int64(56): 55,
 np.int64(57): 56,
 np.int64(58): 57,
 np.int64(59): 58,
 np.int64(60): 59,
 np.int64(61): 60,
 np.int64(62): 61,
 np.int64(63): 62,
 np.int64(64): 63,
 np.int64(65): 64,
 np.int64(66): 65,
 np.int64(67): 66,
 np.int64(68): 67,
 np.int64(69): 68,
 np.int64(70): 69,
 np.int64(71): 70,
 np.int64(72): 71,
 np.int64(73): 72,
 np.int64(74): 73,
 np.int64(75): 74,
 np.int64(76): 75,
 np.int64(77): 76,
 np.int64(78): 77,
 np.int64(79): 78,
 np.int64(80): 79,
 np.int64(81): 80,
 np.int64(82): 81,
 np.int64(83): 82,
 np.int64(84): 83,
 np.int64(85): 84,
 np.int64(86): 85,
 np.int64(87): 86,
 np.int64(88): 87,
 np.int64(89): 88,
 np.int64(90): 89,
 np.int64(92): 90,
 np.int64(93): 91,
 np.int64(94): 92,
 np.int64(95): 93,
 np.int64(96): 94,
 np.int64(97): 95,
 np.int64(98): 96,
 np.int64(99): 97,
 np.int64(100): 98,
 np.int64(101): 99,
 np.int64(102): 100,
 np.int64(103): 101,
 np.int64(104): 102,
 np.int64(105): 103,
 np.int64(106): 104,
 np.int64(107): 105,
 np.int64(108): 106,
 np.int64(109): 107,
 np.int64(110): 108,
 np.int64(111): 109,
 np.int64(112): 110,
 np.int64(113): 111,
 np.int64(114): 112,
 np.int64(115): 113,
 np.int64(116): 114,
 np.int64(117): 115,
 np.int64(118): 116,
 np.int64(119): 117,
 np.int64(120): 118,
 np.int64(121): 119,
 np.int64(122): 120,
 np.int64(123): 121,
 np.int64(124): 122,
 np.int64(125): 123,
 np.int64(126): 124,
 np.int64(127): 125,
 np.int64(128): 126,
 np.int64(129): 127,
 np.int64(130): 128,
 np.int64(131): 129,
 np.int64(132): 130,
 np.int64(133): 131,
 np.int64(134): 132,
 np.int64(135): 133,
 np.int64(136): 134,
 np.int64(137): 135,
 np.int64(138): 136,
 np.int64(139): 137,
 np.int64(140): 138,
 np.int64(141): 139,
 np.int64(142): 140,
 np.int64(143): 141,
 np.int64(144): 142,
 np.int64(145): 143,
 np.int64(146): 144,
 np.int64(147): 145,
 np.int64(148): 146,
 np.int64(149): 147,
 np.int64(150): 148,
 np.int64(151): 149,
 np.int64(152): 150,
 np.int64(153): 151,
 np.int64(154): 152,
 np.int64(155): 153,
 np.int64(156): 154,
 np.int64(157): 155,
 np.int64(158): 156,
 np.int64(159): 157,
 np.int64(160): 158,
 np.int64(161): 159,
 np.int64(162): 160,
 np.int64(163): 161,
 np.int64(164): 162,
 np.int64(165): 163,
 np.int64(166): 164,
 np.int64(167): 165,
 np.int64(168): 166,
 np.int64(169): 167,
 np.int64(170): 168,
 np.int64(171): 169,
 np.int64(172): 170,
 np.int64(173): 171,
 np.int64(174): 172,
 np.int64(175): 173,
 np.int64(176): 174,
 np.int64(177): 175,
 np.int64(178): 176,
 np.int64(179): 177,
 np.int64(180): 178,
 np.int64(181): 179,
 np.int64(182): 180,
 np.int64(183): 181,
 np.int64(184): 182,
 np.int64(185): 183,
 np.int64(186): 184,
 np.int64(187): 185,
 np.int64(188): 186,
 np.int64(189): 187,
 np.int64(190): 188,
 np.int64(191): 189,
 np.int64(192): 190,
 np.int64(193): 191,
 np.int64(194): 192,
 np.int64(195): 193,
 np.int64(196): 194,
 np.int64(197): 195,
 np.int64(198): 196,
 np.int64(199): 197,
 np.int64(200): 198,
 np.int64(201): 199,
 np.int64(202): 200,
 np.int64(203): 201,
 np.int64(204): 202,
 np.int64(205): 203,
 np.int64(206): 204,
 np.int64(207): 205,
 np.int64(208): 206,
 np.int64(209): 207,
 np.int64(210): 208,
 np.int64(211): 209,
 np.int64(212): 210,
 np.int64(213): 211,
 np.int64(214): 212,
 np.int64(215): 213,
 np.int64(216): 214,
 np.int64(217): 215,
 np.int64(218): 216,
 np.int64(219): 217,
 np.int64(220): 218,
 np.int64(222): 219,
 np.int64(223): 220,
 np.int64(224): 221,
 np.int64(225): 222,
 np.int64(226): 223,
 np.int64(227): 224,
 np.int64(228): 225,
 np.int64(229): 226,
 np.int64(230): 227,
 np.int64(231): 228,
 np.int64(232): 229,
 np.int64(233): 230,
 np.int64(234): 231,
 np.int64(235): 232,
 np.int64(236): 233,
 np.int64(237): 234,
 np.int64(238): 235,
 np.int64(239): 236,
 np.int64(240): 237,
 np.int64(241): 238,
 np.int64(242): 239,
 np.int64(243): 240,
 np.int64(244): 241,
 np.int64(245): 242,
 np.int64(246): 243,
 np.int64(247): 244,
 np.int64(248): 245,
 np.int64(249): 246,
 np.int64(250): 247,
 np.int64(251): 248,
 np.int64(252): 249,
 np.int64(253): 250,
 np.int64(254): 251,
 np.int64(255): 252,
 np.int64(256): 253,
 np.int64(257): 254,
 np.int64(258): 255,
 np.int64(259): 256,
 np.int64(260): 257,
 np.int64(261): 258,
 np.int64(262): 259,
 np.int64(263): 260,
 np.int64(264): 261,
 np.int64(265): 262,
 np.int64(266): 263,
 np.int64(267): 264,
 np.int64(268): 265,
 np.int64(269): 266,
 np.int64(270): 267,
 np.int64(271): 268,
 np.int64(272): 269,
 np.int64(273): 270,
 np.int64(274): 271,
 np.int64(275): 272,
 np.int64(276): 273,
 np.int64(277): 274,
 np.int64(278): 275,
 np.int64(279): 276,
 np.int64(280): 277,
 np.int64(281): 278,
 np.int64(282): 279,
 np.int64(283): 280,
 np.int64(284): 281,
 np.int64(285): 282,
 np.int64(286): 283,
 np.int64(287): 284,
 np.int64(288): 285,
 np.int64(289): 286,
 np.int64(290): 287,
 np.int64(291): 288,
 np.int64(292): 289,
 np.int64(293): 290,
 np.int64(294): 291,
 np.int64(295): 292,
 np.int64(296): 293,
 np.int64(297): 294,
 np.int64(298): 295,
 np.int64(299): 296,
 np.int64(300): 297,
 np.int64(301): 298,
 np.int64(302): 299,
 np.int64(303): 300,
 np.int64(304): 301,
 np.int64(305): 302,
 np.int64(306): 303,
 np.int64(307): 304,
 np.int64(308): 305,
 np.int64(309): 306,
 np.int64(310): 307,
 np.int64(311): 308,
 np.int64(312): 309,
 np.int64(313): 310,
 np.int64(314): 311,
 np.int64(315): 312,
 np.int64(316): 313,
 np.int64(317): 314,
 np.int64(318): 315,
 np.int64(319): 316,
 np.int64(320): 317,
 np.int64(321): 318,
 np.int64(322): 319,
 np.int64(324): 320,
 np.int64(325): 321,
 np.int64(326): 322,
 np.int64(327): 323,
 np.int64(328): 324,
 np.int64(329): 325,
 np.int64(330): 326,
 np.int64(331): 327,
 np.int64(332): 328,
 np.int64(333): 329,
 np.int64(334): 330,
 np.int64(335): 331,
 np.int64(336): 332,
 np.int64(337): 333,
 np.int64(338): 334,
 np.int64(339): 335,
 np.int64(340): 336,
 np.int64(341): 337,
 np.int64(342): 338,
 np.int64(343): 339,
 np.int64(344): 340,
 np.int64(345): 341,
 np.int64(346): 342,
 np.int64(347): 343,
 np.int64(348): 344,
 np.int64(349): 345,
 np.int64(350): 346,
 np.int64(351): 347,
 np.int64(352): 348,
 np.int64(353): 349,
 np.int64(354): 350,
 np.int64(355): 351,
 np.int64(356): 352,
 np.int64(357): 353,
 np.int64(358): 354,
 np.int64(359): 355,
 np.int64(360): 356,
 np.int64(361): 357,
 np.int64(362): 358,
 np.int64(363): 359,
 np.int64(364): 360,
 np.int64(365): 361,
 np.int64(366): 362,
 np.int64(367): 363,
 np.int64(368): 364,
 np.int64(369): 365,
 np.int64(370): 366,
 np.int64(371): 367,
 np.int64(372): 368,
 np.int64(373): 369,
 np.int64(374): 370,
 np.int64(375): 371,
 np.int64(376): 372,
 np.int64(377): 373,
 np.int64(378): 374,
 np.int64(379): 375,
 np.int64(380): 376,
 np.int64(381): 377,
 np.int64(382): 378,
 np.int64(383): 379,
 np.int64(384): 380,
 np.int64(385): 381,
 np.int64(386): 382,
 np.int64(387): 383,
 np.int64(388): 384,
 np.int64(389): 385,
 np.int64(390): 386,
 np.int64(391): 387,
 np.int64(392): 388,
 np.int64(393): 389,
 np.int64(394): 390,
 np.int64(395): 391,
 np.int64(396): 392,
 np.int64(397): 393,
 np.int64(398): 394,
 np.int64(399): 395,
 np.int64(400): 396,
 np.int64(401): 397,
 np.int64(402): 398,
 np.int64(403): 399,
 np.int64(404): 400,
 np.int64(405): 401,
 np.int64(406): 402,
 np.int64(407): 403,
 np.int64(408): 404,
 np.int64(409): 405,
 np.int64(410): 406,
 np.int64(411): 407,
 np.int64(412): 408,
 np.int64(413): 409,
 np.int64(414): 410,
 np.int64(415): 411,
 np.int64(416): 412,
 np.int64(417): 413,
 np.int64(418): 414,
 np.int64(419): 415,
 np.int64(420): 416,
 np.int64(421): 417,
 np.int64(422): 418,
 np.int64(423): 419,
 np.int64(424): 420,
 np.int64(425): 421,
 np.int64(426): 422,
 np.int64(427): 423,
 np.int64(428): 424,
 np.int64(429): 425,
 np.int64(430): 426,
 np.int64(431): 427,
 np.int64(432): 428,
 np.int64(433): 429,
 np.int64(434): 430,
 np.int64(435): 431,
 np.int64(436): 432,
 np.int64(437): 433,
 np.int64(438): 434,
 np.int64(439): 435,
 np.int64(440): 436,
 np.int64(441): 437,
 np.int64(442): 438,
 np.int64(443): 439,
 np.int64(444): 440,
 np.int64(445): 441,
 np.int64(446): 442,
 np.int64(447): 443,
 np.int64(448): 444,
 np.int64(449): 445,
 np.int64(450): 446,
 np.int64(451): 447,
 np.int64(452): 448,
 np.int64(453): 449,
 np.int64(454): 450,
 np.int64(455): 451,
 np.int64(456): 452,
 np.int64(457): 453,
 np.int64(458): 454,
 np.int64(459): 455,
 np.int64(460): 456,
 np.int64(461): 457,
 np.int64(462): 458,
 np.int64(463): 459,
 np.int64(464): 460,
 np.int64(465): 461,
 np.int64(466): 462,
 np.int64(467): 463,
 np.int64(468): 464,
 np.int64(469): 465,
 np.int64(470): 466,
 np.int64(471): 467,
 np.int64(472): 468,
 np.int64(473): 469,
 np.int64(474): 470,
 np.int64(475): 471,
 np.int64(476): 472,
 np.int64(477): 473,
 np.int64(478): 474,
 np.int64(479): 475,
 np.int64(480): 476,
 np.int64(481): 477,
 np.int64(482): 478,
 np.int64(483): 479,
 np.int64(484): 480,
 np.int64(485): 481,
 np.int64(486): 482,
 np.int64(487): 483,
 np.int64(488): 484,
 np.int64(489): 485,
 np.int64(490): 486,
 np.int64(491): 487,
 np.int64(492): 488,
 np.int64(493): 489,
 np.int64(494): 490,
 np.int64(495): 491,
 np.int64(496): 492,
 np.int64(497): 493,
 np.int64(498): 494,
 np.int64(499): 495,
 np.int64(500): 496,
 np.int64(501): 497,
 np.int64(502): 498,
 np.int64(503): 499,
 np.int64(504): 500,
 np.int64(505): 501,
 np.int64(506): 502,
 np.int64(507): 503,
 np.int64(508): 504,
 np.int64(509): 505,
 np.int64(510): 506,
 np.int64(511): 507,
 np.int64(512): 508,
 np.int64(513): 509,
 np.int64(514): 510,
 np.int64(515): 511,
 np.int64(516): 512,
 np.int64(517): 513,
 np.int64(518): 514,
 np.int64(519): 515,
 np.int64(520): 516,
 np.int64(521): 517,
 np.int64(522): 518,
 np.int64(523): 519,
 np.int64(524): 520,
 np.int64(525): 521,
 np.int64(526): 522,
 np.int64(527): 523,
 np.int64(528): 524,
 np.int64(529): 525,
 np.int64(530): 526,
 np.int64(531): 527,
 np.int64(532): 528,
 np.int64(533): 529,
 np.int64(534): 530,
 np.int64(535): 531,
 np.int64(536): 532,
 np.int64(537): 533,
 np.int64(538): 534,
 np.int64(539): 535,
 np.int64(540): 536,
 np.int64(541): 537,
 np.int64(542): 538,
 np.int64(543): 539,
 np.int64(544): 540,
 np.int64(545): 541,
 np.int64(546): 542,
 np.int64(547): 543,
 np.int64(548): 544,
 np.int64(549): 545,
 np.int64(550): 546,
 np.int64(551): 547,
 np.int64(552): 548,
 np.int64(553): 549,
 np.int64(554): 550,
 np.int64(555): 551,
 np.int64(556): 552,
 np.int64(557): 553,
 np.int64(558): 554,
 np.int64(559): 555,
 np.int64(560): 556,
 np.int64(561): 557,
 np.int64(562): 558,
 np.int64(563): 559,
 np.int64(564): 560,
 np.int64(565): 561,
 np.int64(566): 562,
 np.int64(567): 563,
 np.int64(568): 564,
 np.int64(569): 565,
 np.int64(570): 566,
 np.int64(571): 567,
 np.int64(572): 568,
 np.int64(573): 569,
 np.int64(574): 570,
 np.int64(575): 571,
 np.int64(576): 572,
 np.int64(577): 573,
 np.int64(578): 574,
 np.int64(579): 575,
 np.int64(580): 576,
 np.int64(581): 577,
 np.int64(582): 578,
 np.int64(583): 579,
 np.int64(584): 580,
 np.int64(585): 581,
 np.int64(586): 582,
 np.int64(587): 583,
 np.int64(588): 584,
 np.int64(589): 585,
 np.int64(590): 586,
 np.int64(591): 587,
 np.int64(592): 588,
 np.int64(593): 589,
 np.int64(594): 590,
 np.int64(595): 591,
 np.int64(596): 592,
 np.int64(597): 593,
 np.int64(598): 594,
 np.int64(599): 595,
 np.int64(600): 596,
 np.int64(601): 597,
 np.int64(602): 598,
 np.int64(603): 599,
 np.int64(604): 600,
 np.int64(605): 601,
 np.int64(606): 602,
 np.int64(607): 603,
 np.int64(608): 604,
 np.int64(609): 605,
 np.int64(610): 606,
 np.int64(611): 607,
 np.int64(612): 608,
 np.int64(613): 609,
 np.int64(614): 610,
 np.int64(615): 611,
 np.int64(616): 612,
 np.int64(617): 613,
 np.int64(618): 614,
 np.int64(619): 615,
 np.int64(620): 616,
 np.int64(621): 617,
 np.int64(623): 618,
 np.int64(624): 619,
 np.int64(625): 620,
 np.int64(626): 621,
 np.int64(627): 622,
 np.int64(628): 623,
 np.int64(629): 624,
 np.int64(630): 625,
 np.int64(631): 626,
 np.int64(632): 627,
 np.int64(633): 628,
 np.int64(634): 629,
 np.int64(635): 630,
 np.int64(636): 631,
 np.int64(637): 632,
 np.int64(638): 633,
 np.int64(639): 634,
 np.int64(640): 635,
 np.int64(641): 636,
 np.int64(642): 637,
 np.int64(643): 638,
 np.int64(644): 639,
 np.int64(645): 640,
 np.int64(647): 641,
 np.int64(648): 642,
 np.int64(649): 643,
 np.int64(650): 644,
 np.int64(651): 645,
 np.int64(652): 646,
 np.int64(653): 647,
 np.int64(654): 648,
 np.int64(655): 649,
 np.int64(656): 650,
 np.int64(657): 651,
 np.int64(658): 652,
 np.int64(659): 653,
 np.int64(660): 654,
 np.int64(661): 655,
 np.int64(662): 656,
 np.int64(663): 657,
 np.int64(664): 658,
 np.int64(665): 659,
 np.int64(666): 660,
 np.int64(667): 661,
 np.int64(668): 662,
 np.int64(669): 663,
 np.int64(670): 664,
 np.int64(671): 665,
 np.int64(672): 666,
 np.int64(673): 667,
 np.int64(674): 668,
 np.int64(675): 669,
 np.int64(676): 670,
 np.int64(678): 671,
 np.int64(679): 672,
 np.int64(680): 673,
 np.int64(681): 674,
 np.int64(682): 675,
 np.int64(683): 676,
 np.int64(684): 677,
 np.int64(685): 678,
 np.int64(687): 679,
 np.int64(688): 680,
 np.int64(690): 681,
 np.int64(691): 682,
 np.int64(692): 683,
 np.int64(693): 684,
 np.int64(694): 685,
 np.int64(695): 686,
 np.int64(696): 687,
 np.int64(697): 688,
 np.int64(698): 689,
 np.int64(699): 690,
 np.int64(700): 691,
 np.int64(701): 692,
 np.int64(702): 693,
 np.int64(703): 694,
 np.int64(704): 695,
 np.int64(705): 696,
 np.int64(706): 697,
 np.int64(707): 698,
 np.int64(708): 699,
 np.int64(709): 700,
 np.int64(710): 701,
 np.int64(711): 702,
 np.int64(712): 703,
 np.int64(713): 704,
 np.int64(714): 705,
 np.int64(715): 706,
 np.int64(716): 707,
 np.int64(717): 708,
 np.int64(718): 709,
 np.int64(719): 710,
 np.int64(720): 711,
 np.int64(721): 712,
 np.int64(722): 713,
 np.int64(723): 714,
 np.int64(724): 715,
 np.int64(725): 716,
 np.int64(726): 717,
 np.int64(727): 718,
 np.int64(728): 719,
 np.int64(729): 720,
 np.int64(730): 721,
 np.int64(731): 722,
 np.int64(732): 723,
 np.int64(733): 724,
 np.int64(734): 725,
 np.int64(735): 726,
 np.int64(736): 727,
 np.int64(737): 728,
 np.int64(738): 729,
 np.int64(739): 730,
 np.int64(741): 731,
 np.int64(742): 732,
 np.int64(743): 733,
 np.int64(744): 734,
 np.int64(745): 735,
 np.int64(746): 736,
 np.int64(747): 737,
 np.int64(748): 738,
 np.int64(749): 739,
 np.int64(750): 740,
 np.int64(751): 741,
 np.int64(752): 742,
 np.int64(753): 743,
 np.int64(754): 744,
 np.int64(755): 745,
 np.int64(756): 746,
 np.int64(757): 747,
 np.int64(758): 748,
 np.int64(759): 749,
 np.int64(760): 750,
 np.int64(761): 751,
 np.int64(762): 752,
 np.int64(763): 753,
 np.int64(764): 754,
 np.int64(765): 755,
 np.int64(766): 756,
 np.int64(767): 757,
 np.int64(768): 758,
 np.int64(769): 759,
 np.int64(770): 760,
 np.int64(771): 761,
 np.int64(772): 762,
 np.int64(773): 763,
 np.int64(774): 764,
 np.int64(775): 765,
 np.int64(776): 766,
 np.int64(777): 767,
 np.int64(778): 768,
 np.int64(779): 769,
 np.int64(780): 770,
 np.int64(781): 771,
 np.int64(782): 772,
 np.int64(783): 773,
 np.int64(784): 774,
 np.int64(785): 775,
 np.int64(786): 776,
 np.int64(787): 777,
 np.int64(788): 778,
 np.int64(789): 779,
 np.int64(790): 780,
 np.int64(791): 781,
 np.int64(792): 782,
 np.int64(793): 783,
 np.int64(794): 784,
 np.int64(795): 785,
 np.int64(796): 786,
 np.int64(797): 787,
 np.int64(798): 788,
 np.int64(799): 789,
 np.int64(800): 790,
 np.int64(801): 791,
 np.int64(802): 792,
 np.int64(803): 793,
 np.int64(804): 794,
 np.int64(805): 795,
 np.int64(806): 796,
 np.int64(807): 797,
 np.int64(808): 798,
 np.int64(809): 799,
 np.int64(810): 800,
 np.int64(811): 801,
 np.int64(812): 802,
 np.int64(813): 803,
 np.int64(814): 804,
 np.int64(815): 805,
 np.int64(816): 806,
 np.int64(818): 807,
 np.int64(819): 808,
 np.int64(820): 809,
 np.int64(821): 810,
 np.int64(822): 811,
 np.int64(823): 812,
 np.int64(824): 813,
 np.int64(825): 814,
 np.int64(826): 815,
 np.int64(827): 816,
 np.int64(828): 817,
 np.int64(829): 818,
 np.int64(830): 819,
 np.int64(831): 820,
 np.int64(832): 821,
 np.int64(833): 822,
 np.int64(834): 823,
 np.int64(835): 824,
 np.int64(836): 825,
 np.int64(837): 826,
 np.int64(838): 827,
 np.int64(839): 828,
 np.int64(840): 829,
 np.int64(841): 830,
 np.int64(842): 831,
 np.int64(843): 832,
 np.int64(844): 833,
 np.int64(845): 834,
 np.int64(846): 835,
 np.int64(847): 836,
 np.int64(848): 837,
 np.int64(849): 838,
 np.int64(850): 839,
 np.int64(851): 840,
 np.int64(852): 841,
 np.int64(853): 842,
 np.int64(854): 843,
 np.int64(855): 844,
 np.int64(856): 845,
 np.int64(857): 846,
 np.int64(858): 847,
 np.int64(859): 848,
 np.int64(860): 849,
 np.int64(861): 850,
 np.int64(862): 851,
 np.int64(863): 852,
 np.int64(864): 853,
 np.int64(865): 854,
 np.int64(866): 855,
 np.int64(867): 856,
 np.int64(868): 857,
 np.int64(869): 858,
 np.int64(870): 859,
 np.int64(871): 860,
 np.int64(872): 861,
 np.int64(873): 862,
 np.int64(874): 863,
 np.int64(875): 864,
 np.int64(876): 865,
 np.int64(877): 866,
 np.int64(878): 867,
 np.int64(879): 868,
 np.int64(880): 869,
 np.int64(881): 870,
 np.int64(882): 871,
 np.int64(884): 872,
 np.int64(885): 873,
 np.int64(886): 874,
 np.int64(887): 875,
 np.int64(888): 876,
 np.int64(889): 877,
 np.int64(890): 878,
 np.int64(891): 879,
 np.int64(892): 880,
 np.int64(893): 881,
 np.int64(894): 882,
 np.int64(895): 883,
 np.int64(896): 884,
 np.int64(897): 885,
 np.int64(898): 886,
 np.int64(899): 887,
 np.int64(900): 888,
 np.int64(901): 889,
 np.int64(902): 890,
 np.int64(903): 891,
 np.int64(904): 892,
 np.int64(905): 893,
 np.int64(906): 894,
 np.int64(907): 895,
 np.int64(908): 896,
 np.int64(909): 897,
 np.int64(910): 898,
 np.int64(911): 899,
 np.int64(912): 900,
 np.int64(913): 901,
 np.int64(914): 902,
 np.int64(915): 903,
 np.int64(916): 904,
 np.int64(917): 905,
 np.int64(918): 906,
 np.int64(919): 907,
 np.int64(920): 908,
 np.int64(921): 909,
 np.int64(922): 910,
 np.int64(923): 911,
 np.int64(924): 912,
 np.int64(925): 913,
 np.int64(926): 914,
 np.int64(927): 915,
 np.int64(928): 916,
 np.int64(929): 917,
 np.int64(930): 918,
 np.int64(931): 919,
 np.int64(932): 920,
 np.int64(933): 921,
 np.int64(934): 922,
 np.int64(935): 923,
 np.int64(936): 924,
 np.int64(937): 925,
 np.int64(938): 926,
 np.int64(939): 927,
 np.int64(940): 928,
 np.int64(941): 929,
 np.int64(942): 930,
 np.int64(943): 931,
 np.int64(944): 932,
 np.int64(945): 933,
 np.int64(946): 934,
 np.int64(947): 935,
 np.int64(948): 936,
 np.int64(949): 937,
 np.int64(950): 938,
 np.int64(951): 939,
 np.int64(952): 940,
 np.int64(953): 941,
 np.int64(954): 942,
 np.int64(955): 943,
 np.int64(956): 944,
 np.int64(957): 945,
 np.int64(958): 946,
 np.int64(959): 947,
 np.int64(960): 948,
 np.int64(961): 949,
 np.int64(962): 950,
 np.int64(963): 951,
 np.int64(964): 952,
 np.int64(965): 953,
 np.int64(966): 954,
 np.int64(967): 955,
 np.int64(968): 956,
 np.int64(969): 957,
 np.int64(970): 958,
 np.int64(971): 959,
 np.int64(972): 960,
 np.int64(973): 961,

In [182]:
movies['item_id']

0          1
1          2
2          3
3          4
4          5
        ...
3878    3948
3879    3949
3880    3950
3881    3951
3882    3952
Name: item_id, Length: 3883, dtype: int64

In [183]:
movies['item_id'] = movies['item_id'].map(item_to_idx)

In [184]:
movies['item_id']

0          0
1          1
2          2
3          3
4          4
        ...
3878    3878
3879    3879
3880    3880
3881    3881
3882    3882
Name: item_id, Length: 3883, dtype: int64

In [185]:
user_to_idx

{np.int64(1): 0,
 np.int64(2): 1,
 np.int64(3): 2,
 np.int64(4): 3,
 np.int64(5): 4,
 np.int64(6): 5,
 np.int64(7): 6,
 np.int64(8): 7,
 np.int64(9): 8,
 np.int64(10): 9,
 np.int64(11): 10,
 np.int64(12): 11,
 np.int64(13): 12,
 np.int64(14): 13,
 np.int64(15): 14,
 np.int64(16): 15,
 np.int64(17): 16,
 np.int64(18): 17,
 np.int64(19): 18,
 np.int64(20): 19,
 np.int64(21): 20,
 np.int64(22): 21,
 np.int64(23): 22,
 np.int64(24): 23,
 np.int64(25): 24,
 np.int64(26): 25,
 np.int64(27): 26,
 np.int64(28): 27,
 np.int64(29): 28,
 np.int64(30): 29,
 np.int64(31): 30,
 np.int64(32): 31,
 np.int64(33): 32,
 np.int64(34): 33,
 np.int64(35): 34,
 np.int64(36): 35,
 np.int64(37): 36,
 np.int64(38): 37,
 np.int64(39): 38,
 np.int64(40): 39,
 np.int64(41): 40,
 np.int64(42): 41,
 np.int64(43): 42,
 np.int64(44): 43,
 np.int64(45): 44,
 np.int64(46): 45,
 np.int64(47): 46,
 np.int64(48): 47,
 np.int64(49): 48,
 np.int64(50): 49,
 np.int64(51): 50,
 np.int64(52): 51,
 np.int64(53): 52,
 np.int64(54): 53,
 np.int64(55): 54,
 np.int64(56): 55,
 np.int64(57): 56,
 np.int64(58): 57,
 np.int64(59): 58,
 np.int64(60): 59,
 np.int64(61): 60,
 np.int64(62): 61,
 np.int64(63): 62,
 np.int64(64): 63,
 np.int64(65): 64,
 np.int64(66): 65,
 np.int64(67): 66,
 np.int64(68): 67,
 np.int64(69): 68,
 np.int64(70): 69,
 np.int64(71): 70,
 np.int64(72): 71,
 np.int64(73): 72,
 np.int64(74): 73,
 np.int64(75): 74,
 np.int64(76): 75,
 np.int64(77): 76,
 np.int64(78): 77,
 np.int64(79): 78,
 np.int64(80): 79,
 np.int64(81): 80,
 np.int64(82): 81,
 np.int64(83): 82,
 np.int64(84): 83,
 np.int64(85): 84,
 np.int64(86): 85,
 np.int64(87): 86,
 np.int64(88): 87,
 np.int64(89): 88,
 np.int64(90): 89,
 np.int64(91): 90,
 np.int64(92): 91,
 np.int64(93): 92,
 np.int64(94): 93,
 np.int64(95): 94,
 np.int64(96): 95,
 np.int64(97): 96,
 np.int64(98): 97,
 np.int64(99): 98,
 np.int64(100): 99,
 np.int64(101): 100,
 np.int64(102): 101,
 np.int64(103): 102,
 np.int64(104): 103,
 np.int64(105): 104,
 np.int64(106): 105,
 np.int64(107): 106,
 np.int64(108): 107,
 np.int64(109): 108,
 np.int64(110): 109,
 np.int64(111): 110,
 np.int64(112): 111,
 np.int64(113): 112,
 np.int64(114): 113,
 np.int64(115): 114,
 np.int64(116): 115,
 np.int64(117): 116,
 np.int64(118): 117,
 np.int64(119): 118,
 np.int64(120): 119,
 np.int64(121): 120,
 np.int64(122): 121,
 np.int64(123): 122,
 np.int64(124): 123,
 np.int64(125): 124,
 np.int64(126): 125,
 np.int64(127): 126,
 np.int64(128): 127,
 np.int64(129): 128,
 np.int64(130): 129,
 np.int64(131): 130,
 np.int64(132): 131,
 np.int64(133): 132,
 np.int64(134): 133,
 np.int64(135): 134,
 np.int64(136): 135,
 np.int64(137): 136,
 np.int64(138): 137,
 np.int64(139): 138,
 np.int64(140): 139,
 np.int64(141): 140,
 np.int64(142): 141,
 np.int64(143): 142,
 np.int64(144): 143,
 np.int64(145): 144,
 np.int64(146): 145,
 np.int64(147): 146,
 np.int64(148): 147,
 np.int64(149): 148,
 np.int64(150): 149,
 np.int64(151): 150,
 np.int64(152): 151,
 np.int64(153): 152,
 np.int64(154): 153,
 np.int64(155): 154,
 np.int64(156): 155,
 np.int64(157): 156,
 np.int64(158): 157,
 np.int64(159): 158,
 np.int64(160): 159,
 np.int64(161): 160,
 np.int64(162): 161,
 np.int64(163): 162,
 np.int64(164): 163,
 np.int64(165): 164,
 np.int64(166): 165,
 np.int64(167): 166,
 np.int64(168): 167,
 np.int64(169): 168,
 np.int64(170): 169,
 np.int64(171): 170,
 np.int64(172): 171,
 np.int64(173): 172,
 np.int64(174): 173,
 np.int64(175): 174,
 np.int64(176): 175,
 np.int64(177): 176,
 np.int64(178): 177,
 np.int64(179): 178,
 np.int64(180): 179,
 np.int64(181): 180,
 np.int64(182): 181,
 np.int64(183): 182,
 np.int64(184): 183,
 np.int64(185): 184,
 np.int64(186): 185,
 np.int64(187): 186,
 np.int64(188): 187,
 np.int64(189): 188,
 np.int64(190): 189,
 np.int64(191): 190,
 np.int64(192): 191,
 np.int64(193): 192,
 np.int64(194): 193,
 np.int64(195): 194,
 np.int64(196): 195,
 np.int64(197): 196,
 np.int64(198): 197,
 np.int64(199): 198,
 np.int64(200): 199,
 np.int64(201): 200,
 np.int64(202): 201,
 np.int64(203): 202,
 np.int64(204): 203,
 np.int64(205): 204,
 np.int64(206): 205,
 np.int64(207): 206,
 np.int64(208): 207,
 np.int64(209): 208,
 np.int64(210): 209,
 np.int64(211): 210,
 np.int64(212): 211,
 np.int64(213): 212,
 np.int64(214): 213,
 np.int64(215): 214,
 np.int64(216): 215,
 np.int64(217): 216,
 np.int64(218): 217,
 np.int64(219): 218,
 np.int64(220): 219,
 np.int64(221): 220,
 np.int64(222): 221,
 np.int64(223): 222,
 np.int64(224): 223,
 np.int64(225): 224,
 np.int64(226): 225,
 np.int64(227): 226,
 np.int64(228): 227,
 np.int64(229): 228,
 np.int64(230): 229,
 np.int64(231): 230,
 np.int64(232): 231,
 np.int64(233): 232,
 np.int64(234): 233,
 np.int64(235): 234,
 np.int64(236): 235,
 np.int64(237): 236,
 np.int64(238): 237,
 np.int64(239): 238,
 np.int64(240): 239,
 np.int64(241): 240,
 np.int64(242): 241,
 np.int64(243): 242,
 np.int64(244): 243,
 np.int64(245): 244,
 np.int64(246): 245,
 np.int64(247): 246,
 np.int64(248): 247,
 np.int64(249): 248,
 np.int64(250): 249,
 np.int64(251): 250,
 np.int64(252): 251,
 np.int64(253): 252,
 np.int64(254): 253,
 np.int64(255): 254,
 np.int64(256): 255,
 np.int64(257): 256,
 np.int64(258): 257,
 np.int64(259): 258,
 np.int64(260): 259,
 np.int64(261): 260,
 np.int64(262): 261,
 np.int64(263): 262,
 np.int64(264): 263,
 np.int64(265): 264,
 np.int64(266): 265,
 np.int64(267): 266,
 np.int64(268): 267,
 np.int64(269): 268,
 np.int64(270): 269,
 np.int64(271): 270,
 np.int64(272): 271,
 np.int64(273): 272,
 np.int64(274): 273,
 np.int64(275): 274,
 np.int64(276): 275,
 np.int64(277): 276,
 np.int64(278): 277,
 np.int64(279): 278,
 np.int64(280): 279,
 np.int64(281): 280,
 np.int64(282): 281,
 np.int64(283): 282,
 np.int64(284): 283,
 np.int64(285): 284,
 np.int64(286): 285,
 np.int64(287): 286,
 np.int64(288): 287,
 np.int64(289): 288,
 np.int64(290): 289,
 np.int64(291): 290,
 np.int64(292): 291,
 np.int64(293): 292,
 np.int64(294): 293,
 np.int64(295): 294,
 np.int64(296): 295,
 np.int64(297): 296,
 np.int64(298): 297,
 np.int64(299): 298,
 np.int64(300): 299,
 np.int64(301): 300,
 np.int64(302): 301,
 np.int64(303): 302,
 np.int64(304): 303,
 np.int64(305): 304,
 np.int64(306): 305,
 np.int64(307): 306,
 np.int64(308): 307,
 np.int64(309): 308,
 np.int64(310): 309,
 np.int64(311): 310,
 np.int64(312): 311,
 np.int64(313): 312,
 np.int64(314): 313,
 np.int64(315): 314,
 np.int64(316): 315,
 np.int64(317): 316,
 np.int64(318): 317,
 np.int64(319): 318,
 np.int64(320): 319,
 np.int64(321): 320,
 np.int64(322): 321,
 np.int64(323): 322,
 np.int64(324): 323,
 np.int64(325): 324,
 np.int64(326): 325,
 np.int64(327): 326,
 np.int64(328): 327,
 np.int64(329): 328,
 np.int64(330): 329,
 np.int64(331): 330,
 np.int64(332): 331,
 np.int64(333): 332,
 np.int64(334): 333,
 np.int64(335): 334,
 np.int64(336): 335,
 np.int64(337): 336,
 np.int64(338): 337,
 np.int64(339): 338,
 np.int64(340): 339,
 np.int64(341): 340,
 np.int64(342): 341,
 np.int64(343): 342,
 np.int64(344): 343,
 np.int64(345): 344,
 np.int64(346): 345,
 np.int64(347): 346,
 np.int64(348): 347,
 np.int64(349): 348,
 np.int64(350): 349,
 np.int64(351): 350,
 np.int64(352): 351,
 np.int64(353): 352,
 np.int64(354): 353,
 np.int64(355): 354,
 np.int64(356): 355,
 np.int64(357): 356,
 np.int64(358): 357,
 np.int64(359): 358,
 np.int64(360): 359,
 np.int64(361): 360,
 np.int64(362): 361,
 np.int64(363): 362,
 np.int64(364): 363,
 np.int64(365): 364,
 np.int64(366): 365,
 np.int64(367): 366,
 np.int64(368): 367,
 np.int64(369): 368,
 np.int64(370): 369,
 np.int64(371): 370,
 np.int64(372): 371,
 np.int64(373): 372,
 np.int64(374): 373,
 np.int64(375): 374,
 np.int64(376): 375,
 np.int64(377): 376,
 np.int64(378): 377,
 np.int64(379): 378,
 np.int64(380): 379,
 np.int64(381): 380,
 np.int64(382): 381,
 np.int64(383): 382,
 np.int64(384): 383,
 np.int64(385): 384,
 np.int64(386): 385,
 np.int64(387): 386,
 np.int64(388): 387,
 np.int64(389): 388,
 np.int64(390): 389,
 np.int64(391): 390,
 np.int64(392): 391,
 np.int64(393): 392,
 np.int64(394): 393,
 np.int64(395): 394,
 np.int64(396): 395,
 np.int64(397): 396,
 np.int64(398): 397,
 np.int64(399): 398,
 np.int64(400): 399,
 np.int64(401): 400,
 np.int64(402): 401,
 np.int64(403): 402,
 np.int64(404): 403,
 np.int64(405): 404,
 np.int64(406): 405,
 np.int64(407): 406,
 np.int64(408): 407,
 np.int64(409): 408,
 np.int64(410): 409,
 np.int64(411): 410,
 np.int64(412): 411,
 np.int64(413): 412,
 np.int64(414): 413,
 np.int64(415): 414,
 np.int64(416): 415,
 np.int64(417): 416,
 np.int64(418): 417,
 np.int64(419): 418,
 np.int64(420): 419,
 np.int64(421): 420,
 np.int64(422): 421,
 np.int64(423): 422,
 np.int64(424): 423,
 np.int64(425): 424,
 np.int64(426): 425,
 np.int64(427): 426,
 np.int64(428): 427,
 np.int64(429): 428,
 np.int64(430): 429,
 np.int64(431): 430,
 np.int64(432): 431,
 np.int64(433): 432,
 np.int64(434): 433,
 np.int64(435): 434,
 np.int64(436): 435,
 np.int64(437): 436,
 np.int64(438): 437,
 np.int64(439): 438,
 np.int64(440): 439,
 np.int64(441): 440,
 np.int64(442): 441,
 np.int64(443): 442,
 np.int64(444): 443,
 np.int64(445): 444,
 np.int64(446): 445,
 np.int64(447): 446,
 np.int64(448): 447,
 np.int64(449): 448,
 np.int64(450): 449,
 np.int64(451): 450,
 np.int64(452): 451,
 np.int64(453): 452,
 np.int64(454): 453,
 np.int64(455): 454,
 np.int64(456): 455,
 np.int64(457): 456,
 np.int64(458): 457,
 np.int64(459): 458,
 np.int64(460): 459,
 np.int64(461): 460,
 np.int64(462): 461,
 np.int64(463): 462,
 np.int64(464): 463,
 np.int64(465): 464,
 np.int64(466): 465,
 np.int64(467): 466,
 np.int64(468): 467,
 np.int64(469): 468,
 np.int64(470): 469,
 np.int64(471): 470,
 np.int64(472): 471,
 np.int64(473): 472,
 np.int64(474): 473,
 np.int64(475): 474,
 np.int64(476): 475,
 np.int64(477): 476,
 np.int64(478): 477,
 np.int64(479): 478,
 np.int64(480): 479,
 np.int64(481): 480,
 np.int64(482): 481,
 np.int64(483): 482,
 np.int64(484): 483,
 np.int64(485): 484,
 np.int64(486): 485,
 np.int64(487): 486,
 np.int64(488): 487,
 np.int64(489): 488,
 np.int64(490): 489,
 np.int64(491): 490,
 np.int64(492): 491,
 np.int64(493): 492,
 np.int64(494): 493,
 np.int64(495): 494,
 np.int64(496): 495,
 np.int64(497): 496,
 np.int64(498): 497,
 np.int64(499): 498,
 np.int64(500): 499,
 np.int64(501): 500,
 np.int64(502): 501,
 np.int64(503): 502,
 np.int64(504): 503,
 np.int64(505): 504,
 np.int64(506): 505,
 np.int64(507): 506,
 np.int64(508): 507,
 np.int64(509): 508,
 np.int64(510): 509,
 np.int64(511): 510,
 np.int64(512): 511,
 np.int64(513): 512,
 np.int64(514): 513,
 np.int64(515): 514,
 np.int64(516): 515,
 np.int64(517): 516,
 np.int64(518): 517,
 np.int64(519): 518,
 np.int64(520): 519,
 np.int64(521): 520,
 np.int64(522): 521,
 np.int64(523): 522,
 np.int64(524): 523,
 np.int64(525): 524,
 np.int64(526): 525,
 np.int64(527): 526,
 np.int64(528): 527,
 np.int64(529): 528,
 np.int64(530): 529,
 np.int64(531): 530,
 np.int64(532): 531,
 np.int64(533): 532,
 np.int64(534): 533,
 np.int64(535): 534,
 np.int64(536): 535,
 np.int64(537): 536,
 np.int64(538): 537,
 np.int64(539): 538,
 np.int64(540): 539,
 np.int64(541): 540,
 np.int64(542): 541,
 np.int64(543): 542,
 np.int64(544): 543,
 np.int64(545): 544,
 np.int64(546): 545,
 np.int64(547): 546,
 np.int64(548): 547,
 np.int64(549): 548,
 np.int64(550): 549,
 np.int64(551): 550,
 np.int64(552): 551,
 np.int64(553): 552,
 np.int64(554): 553,
 np.int64(555): 554,
 np.int64(556): 555,
 np.int64(557): 556,
 np.int64(558): 557,
 np.int64(559): 558,
 np.int64(560): 559,
 np.int64(561): 560,
 np.int64(562): 561,
 np.int64(563): 562,
 np.int64(564): 563,
 np.int64(565): 564,
 np.int64(566): 565,
 np.int64(567): 566,
 np.int64(568): 567,
 np.int64(569): 568,
 np.int64(570): 569,
 np.int64(571): 570,
 np.int64(572): 571,
 np.int64(573): 572,
 np.int64(574): 573,
 np.int64(575): 574,
 np.int64(576): 575,
 np.int64(577): 576,
 np.int64(578): 577,
 np.int64(579): 578,
 np.int64(580): 579,
 np.int64(581): 580,
 np.int64(582): 581,
 np.int64(583): 582,
 np.int64(584): 583,
 np.int64(585): 584,
 np.int64(586): 585,
 np.int64(587): 586,
 np.int64(588): 587,
 np.int64(589): 588,
 np.int64(590): 589,
 np.int64(591): 590,
 np.int64(592): 591,
 np.int64(593): 592,
 np.int64(594): 593,
 np.int64(595): 594,
 np.int64(596): 595,
 np.int64(597): 596,
 np.int64(598): 597,
 np.int64(599): 598,
 np.int64(600): 599,
 np.int64(601): 600,
 np.int64(602): 601,
 np.int64(603): 602,
 np.int64(604): 603,
 np.int64(605): 604,
 np.int64(606): 605,
 np.int64(607): 606,
 np.int64(608): 607,
 np.int64(609): 608,
 np.int64(610): 609,
 np.int64(611): 610,
 np.int64(612): 611,
 np.int64(613): 612,
 np.int64(614): 613,
 np.int64(615): 614,
 np.int64(616): 615,
 np.int64(617): 616,
 np.int64(618): 617,
 np.int64(619): 618,
 np.int64(620): 619,
 np.int64(621): 620,
 np.int64(622): 621,
 np.int64(623): 622,
 np.int64(624): 623,
 np.int64(625): 624,
 np.int64(626): 625,
 np.int64(627): 626,
 np.int64(628): 627,
 np.int64(629): 628,
 np.int64(630): 629,
 np.int64(631): 630,
 np.int64(632): 631,
 np.int64(633): 632,
 np.int64(634): 633,
 np.int64(635): 634,
 np.int64(636): 635,
 np.int64(637): 636,
 np.int64(638): 637,
 np.int64(639): 638,
 np.int64(640): 639,
 np.int64(641): 640,
 np.int64(642): 641,
 np.int64(643): 642,
 np.int64(644): 643,
 np.int64(645): 644,
 np.int64(646): 645,
 np.int64(647): 646,
 np.int64(648): 647,
 np.int64(649): 648,
 np.int64(650): 649,
 np.int64(651): 650,
 np.int64(652): 651,
 np.int64(653): 652,
 np.int64(654): 653,
 np.int64(655): 654,
 np.int64(656): 655,
 np.int64(657): 656,
 np.int64(658): 657,
 np.int64(659): 658,
 np.int64(660): 659,
 np.int64(661): 660,
 np.int64(662): 661,
 np.int64(663): 662,
 np.int64(664): 663,
 np.int64(665): 664,
 np.int64(666): 665,
 np.int64(667): 666,
 np.int64(668): 667,
 np.int64(669): 668,
 np.int64(670): 669,
 np.int64(671): 670,
 np.int64(672): 671,
 np.int64(673): 672,
 np.int64(674): 673,
 np.int64(675): 674,
 np.int64(676): 675,
 np.int64(677): 676,
 np.int64(678): 677,
 np.int64(679): 678,
 np.int64(680): 679,
 np.int64(681): 680,
 np.int64(682): 681,
 np.int64(683): 682,
 np.int64(684): 683,
 np.int64(685): 684,
 np.int64(686): 685,
 np.int64(687): 686,
 np.int64(688): 687,
 np.int64(689): 688,
 np.int64(690): 689,
 np.int64(691): 690,
 np.int64(692): 691,
 np.int64(693): 692,
 np.int64(694): 693,
 np.int64(695): 694,
 np.int64(696): 695,
 np.int64(697): 696,
 np.int64(698): 697,
 np.int64(699): 698,
 np.int64(700): 699,
 np.int64(701): 700,
 np.int64(702): 701,
 np.int64(703): 702,
 np.int64(704): 703,
 np.int64(705): 704,
 np.int64(706): 705,
 np.int64(707): 706,
 np.int64(708): 707,
 np.int64(709): 708,
 np.int64(710): 709,
 np.int64(711): 710,
 np.int64(712): 711,
 np.int64(713): 712,
 np.int64(714): 713,
 np.int64(715): 714,
 np.int64(716): 715,
 np.int64(717): 716,
 np.int64(718): 717,
 np.int64(719): 718,
 np.int64(720): 719,
 np.int64(721): 720,
 np.int64(722): 721,
 np.int64(723): 722,
 np.int64(724): 723,
 np.int64(725): 724,
 np.int64(726): 725,
 np.int64(727): 726,
 np.int64(728): 727,
 np.int64(729): 728,
 np.int64(730): 729,
 np.int64(731): 730,
 np.int64(732): 731,
 np.int64(733): 732,
 np.int64(734): 733,
 np.int64(735): 734,
 np.int64(736): 735,
 np.int64(737): 736,
 np.int64(738): 737,
 np.int64(739): 738,
 np.int64(740): 739,
 np.int64(741): 740,
 np.int64(742): 741,
 np.int64(743): 742,
 np.int64(744): 743,
 np.int64(745): 744,
 np.int64(746): 745,
 np.int64(747): 746,
 np.int64(748): 747,
 np.int64(749): 748,
 np.int64(750): 749,
 np.int64(751): 750,
 np.int64(752): 751,
 np.int64(753): 752,
 np.int64(754): 753,
 np.int64(755): 754,
 np.int64(756): 755,
 np.int64(757): 756,
 np.int64(758): 757,
 np.int64(759): 758,
 np.int64(760): 759,
 np.int64(761): 760,
 np.int64(762): 761,
 np.int64(763): 762,
 np.int64(764): 763,
 np.int64(765): 764,
 np.int64(766): 765,
 np.int64(767): 766,
 np.int64(768): 767,
 np.int64(769): 768,
 np.int64(770): 769,
 np.int64(771): 770,
 np.int64(772): 771,
 np.int64(773): 772,
 np.int64(774): 773,
 np.int64(775): 774,
 np.int64(776): 775,
 np.int64(777): 776,
 np.int64(778): 777,
 np.int64(779): 778,
 np.int64(780): 779,
 np.int64(781): 780,
 np.int64(782): 781,
 np.int64(783): 782,
 np.int64(784): 783,
 np.int64(785): 784,
 np.int64(786): 785,
 np.int64(787): 786,
 np.int64(788): 787,
 np.int64(789): 788,
 np.int64(790): 789,
 np.int64(791): 790,
 np.int64(792): 791,
 np.int64(793): 792,
 np.int64(794): 793,
 np.int64(795): 794,
 np.int64(796): 795,
 np.int64(797): 796,
 np.int64(798): 797,
 np.int64(799): 798,
 np.int64(800): 799,
 np.int64(801): 800,
 np.int64(802): 801,
 np.int64(803): 802,
 np.int64(804): 803,
 np.int64(805): 804,
 np.int64(806): 805,
 np.int64(807): 806,
 np.int64(808): 807,
 np.int64(809): 808,
 np.int64(810): 809,
 np.int64(811): 810,
 np.int64(812): 811,
 np.int64(813): 812,
 np.int64(814): 813,
 np.int64(815): 814,
 np.int64(816): 815,
 np.int64(817): 816,
 np.int64(818): 817,
 np.int64(819): 818,
 np.int64(820): 819,
 np.int64(821): 820,
 np.int64(822): 821,
 np.int64(823): 822,
 np.int64(824): 823,
 np.int64(825): 824,
 np.int64(826): 825,
 np.int64(827): 826,
 np.int64(828): 827,
 np.int64(829): 828,
 np.int64(830): 829,
 np.int64(831): 830,
 np.int64(832): 831,
 np.int64(833): 832,
 np.int64(834): 833,
 np.int64(835): 834,
 np.int64(836): 835,
 np.int64(837): 836,
 np.int64(838): 837,
 np.int64(839): 838,
 np.int64(840): 839,
 np.int64(841): 840,
 np.int64(842): 841,
 np.int64(843): 842,
 np.int64(844): 843,
 np.int64(845): 844,
 np.int64(846): 845,
 np.int64(847): 846,
 np.int64(848): 847,
 np.int64(849): 848,
 np.int64(850): 849,
 np.int64(851): 850,
 np.int64(852): 851,
 np.int64(853): 852,
 np.int64(854): 853,
 np.int64(855): 854,
 np.int64(856): 855,
 np.int64(857): 856,
 np.int64(858): 857,
 np.int64(859): 858,
 np.int64(860): 859,
 np.int64(861): 860,
 np.int64(862): 861,
 np.int64(863): 862,
 np.int64(864): 863,
 np.int64(865): 864,
 np.int64(866): 865,
 np.int64(867): 866,
 np.int64(868): 867,
 np.int64(869): 868,
 np.int64(870): 869,
 np.int64(871): 870,
 np.int64(872): 871,
 np.int64(873): 872,
 np.int64(874): 873,
 np.int64(875): 874,
 np.int64(876): 875,
 np.int64(877): 876,
 np.int64(878): 877,
 np.int64(879): 878,
 np.int64(880): 879,
 np.int64(881): 880,
 np.int64(882): 881,
 np.int64(883): 882,
 np.int64(884): 883,
 np.int64(885): 884,
 np.int64(886): 885,
 np.int64(887): 886,
 np.int64(888): 887,
 np.int64(889): 888,
 np.int64(890): 889,
 np.int64(891): 890,
 np.int64(892): 891,
 np.int64(893): 892,
 np.int64(894): 893,
 np.int64(895): 894,
 np.int64(896): 895,
 np.int64(897): 896,
 np.int64(898): 897,
 np.int64(899): 898,
 np.int64(900): 899,
 np.int64(901): 900,
 np.int64(902): 901,
 np.int64(903): 902,
 np.int64(904): 903,
 np.int64(905): 904,
 np.int64(906): 905,
 np.int64(907): 906,
 np.int64(908): 907,
 np.int64(909): 908,
 np.int64(910): 909,
 np.int64(911): 910,
 np.int64(912): 911,
 np.int64(913): 912,
 np.int64(914): 913,
 np.int64(915): 914,
 np.int64(916): 915,
 np.int64(917): 916,
 np.int64(918): 917,
 np.int64(919): 918,
 np.int64(920): 919,
 np.int64(921): 920,
 np.int64(922): 921,
 np.int64(923): 922,
 np.int64(924): 923,
 np.int64(925): 924,
 np.int64(926): 925,
 np.int64(927): 926,
 np.int64(928): 927,
 np.int64(929): 928,
 np.int64(930): 929,
 np.int64(931): 930,
 np.int64(932): 931,
 np.int64(933): 932,
 np.int64(934): 933,
 np.int64(935): 934,
 np.int64(936): 935,
 np.int64(937): 936,
 np.int64(938): 937,
 np.int64(939): 938,
 np.int64(940): 939,
 np.int64(941): 940,
 np.int64(942): 941,
 np.int64(943): 942,
 np.int64(944): 943,
 np.int64(945): 944,
 np.int64(946): 945,
 np.int64(947): 946,
 np.int64(948): 947,
 np.int64(949): 948,
 np.int64(950): 949,
 np.int64(951): 950,
 np.int64(952): 951,
 np.int64(953): 952,
 np.int64(954): 953,
 np.int64(955): 954,
 np.int64(956): 955,
 np.int64(957): 956,
 np.int64(958): 957,
 np.int64(959): 958,
 np.int64(960): 959,
 np.int64(961): 960,
 np.int64(962): 961,

In [186]:
users['user_id']

0          0
1          1
2          2
3          3
4          4
        ...
6035    6035
6036    6036
6037    6037
6038    6038
6039    6039
Name: user_id, Length: 6040, dtype: int64

In [187]:
movies['genres'].value_counts()

genres
Drama                              843
Comedy                             521
Horror                             178
Comedy|Drama                       162
Comedy|Romance                     142
                                  ...
Drama|Film-Noir                      1
Comedy|Horror|Sci-Fi                 1
Adventure|Drama|Romance|Sci-Fi       1
Adventure|Animation|Sci-Fi           1
Adventure|Crime|Sci-Fi|Thriller      1
Name: count, Length: 301, dtype: int64

In [188]:
movies['genre_list'] = movies['genres'].apply(lambda x: x.split('|'))

In [189]:
movies['genre_list']

0        [Animation, Children's, Comedy]
1       [Adventure, Children's, Fantasy]
2                      [Comedy, Romance]
3                        [Comedy, Drama]
4                               [Comedy]
                      ...
3878                            [Comedy]
3879                             [Drama]
3880                             [Drama]
3881                             [Drama]
3882                   [Drama, Thriller]
Name: genre_list, Length: 3883, dtype: object

In [190]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
genre_matrix = mlb.fit_transform(movies['genre_list'])
num_genres = len(mlb.classes_)

In [191]:
num_items,num_genres,num_users

(3883, 18, 6040)

In [192]:
mlb.classes_

array(['Action', 'Adventure', 'Animation', "Children's", 'Comedy',
       'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War',
       'Western'], dtype=object)

In [193]:
users

      user_id  gender  age  occupation    zip
0           0       1    1          10  48067
1           1       0   56          16  70072
2           2       0   25          15  55117
3           3       0   45           7  02460
4           4       0   25          20  55455
...       ...     ...  ...         ...    ...
6035     6035       1   25          15  32603
6036     6036       1   45           1  76006
6037     6037       1   56           1  14706
6038     6038       1   45           0  01060
6039     6039       0   25           6  11106

[6040 rows x 5 columns]

In [194]:
user_meta_df = users.sort_values('user_id')[['gender', 'age', 'occupation']]

In [195]:
genre_df = pd.DataFrame(
    genre_matrix,
    columns=mlb.classes_,   # e.g. ['Action', 'Comedy', 'Drama', ...]
    index=movies.index
)

In [196]:
genre_df

,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3879,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3880,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3881,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3882,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0

In [197]:
movies = pd.concat([movies, genre_df], axis=1)

In [198]:
movies

,item_id,title,genres,genre_list,Action,Adventure,Animation,Children's,Comedy,Crime,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,Toy Story (1995),Animation|Children's|Comedy,"[Animation, Children's, Comedy]",0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,1,Jumanji (1995),Adventure|Children's|Fantasy,"[Adventure, Children's, Fantasy]",0,1,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
2,2,Grumpier Old Men (1995),Comedy|Romance,"[Comedy, Romance]",0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
3,3,Waiting to Exhale (1995),Comedy|Drama,"[Comedy, Drama]",0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,4,Father of the Bride Part II (1995),Comedy,[Comedy],0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,3878,Meet the Parents (2000),Comedy,[Comedy],0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3879,3879,Requiem for a Dream (2000),Drama,[Drama],0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3880,3880,Tigerland (2000),Drama,[Drama],0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3881,3881,Two Family House (2000),Drama,[Drama],0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3882,3882,"Contender, The (2000)",Drama|Thriller,"[Drama, Thriller]",0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [199]:
genre_matrix

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], shape=(3883, 18))

In [200]:
train_ratings

         user_id  item_id  timestamp  target
31             0     3117  978300019       1
22             0     1250  978300055       1
27             0     1672  978300055       1
37             0     1009  978300055       1
24             0     2271  978300103       1
...          ...      ...        ...     ...
999923      6039      229  997454398       1
1000019     6039     2848  997454429       1
999988      6039     1852  997454464       1
1000172     6039     1726  997454464       1
1000167     6039      159  997454486       1

[994169 rows x 4 columns]

In [201]:
idx_to_user = {idx: raw_id for raw_id, idx in user_to_idx.items()}
idx_to_item = {idx: raw_id for raw_id, idx in item_to_idx.items()}

In [202]:
movies

,item_id,title,genres,genre_list,Action,Adventure,Animation,Children's,Comedy,Crime,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,Toy Story (1995),Animation|Children's|Comedy,"[Animation, Children's, Comedy]",0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,1,Jumanji (1995),Adventure|Children's|Fantasy,"[Adventure, Children's, Fantasy]",0,1,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
2,2,Grumpier Old Men (1995),Comedy|Romance,"[Comedy, Romance]",0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
3,3,Waiting to Exhale (1995),Comedy|Drama,"[Comedy, Drama]",0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,4,Father of the Bride Part II (1995),Comedy,[Comedy],0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,3878,Meet the Parents (2000),Comedy,[Comedy],0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3879,3879,Requiem for a Dream (2000),Drama,[Drama],0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3880,3880,Tigerland (2000),Drama,[Drama],0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3881,3881,Two Family House (2000),Drama,[Drama],0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3882,3882,"Contender, The (2000)",Drama|Thriller,"[Drama, Thriller]",0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [203]:
# Assuming your preprocessed movies DataFrame has 'item_id' (0 to N-1) and 'title'
idx_to_title = dict(zip(movies['item_id'], movies['title']))

In [204]:
idx_to_title

{0: 'Toy Story (1995)',
 1: 'Jumanji (1995)',
 2: 'Grumpier Old Men (1995)',
 3: 'Waiting to Exhale (1995)',
 4: 'Father of the Bride Part II (1995)',
 5: 'Heat (1995)',
 6: 'Sabrina (1995)',
 7: 'Tom and Huck (1995)',
 8: 'Sudden Death (1995)',
 9: 'GoldenEye (1995)',
 10: 'American President, The (1995)',
 11: 'Dracula: Dead and Loving It (1995)',
 12: 'Balto (1995)',
 13: 'Nixon (1995)',
 14: 'Cutthroat Island (1995)',
 15: 'Casino (1995)',
 16: 'Sense and Sensibility (1995)',
 17: 'Four Rooms (1995)',
 18: 'Ace Ventura: When Nature Calls (1995)',
 19: 'Money Train (1995)',
 20: 'Get Shorty (1995)',
 21: 'Copycat (1995)',
 22: 'Assassins (1995)',
 23: 'Powder (1995)',
 24: 'Leaving Las Vegas (1995)',
 25: 'Othello (1995)',
 26: 'Now and Then (1995)',
 27: 'Persuasion (1995)',
 28: 'City of Lost Children, The (1995)',
 29: 'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)',
 30: 'Dangerous Minds (1995)',
 31: 'Twelve Monkeys (1995)',
 32: 'Wings of Courage (1995)',
 33: 'Babe (1995)',
 34: 'Carrington (1995)',
 35: 'Dead Man Walking (1995)',
 36: 'Across the Sea of Time (1995)',
 37: 'It Takes Two (1995)',
 38: 'Clueless (1995)',
 39: 'Cry, the Beloved Country (1995)',
 40: 'Richard III (1995)',
 41: 'Dead Presidents (1995)',
 42: 'Restoration (1995)',
 43: 'Mortal Kombat (1995)',
 44: 'To Die For (1995)',
 45: 'How to Make an American Quilt (1995)',
 46: 'Seven (Se7en) (1995)',
 47: 'Pocahontas (1995)',
 48: 'When Night Is Falling (1995)',
 49: 'Usual Suspects, The (1995)',
 50: 'Guardian Angel (1994)',
 51: 'Mighty Aphrodite (1995)',
 52: 'Lamerica (1994)',
 53: 'Big Green, The (1995)',
 54: 'Georgia (1995)',
 55: 'Kids of the Round Table (1995)',
 56: 'Home for the Holidays (1995)',
 57: 'Postino, Il (The Postman) (1994)',
 58: 'Confessional, The (Le Confessionnal) (1995)',
 59: 'Indian in the Cupboard, The (1995)',
 60: 'Eye for an Eye (1996)',
 61: "Mr. Holland's Opus (1995)",
 62: "Don't Be a Menace to South Central While Drinking Your Juice in the Hood (1996)",
 63: 'Two if by Sea (1996)',
 64: 'Bio-Dome (1996)',
 65: 'Lawnmower Man 2: Beyond Cyberspace (1996)',
 66: 'Two Bits (1995)',
 67: 'French Twist (Gazon maudit) (1995)',
 68: 'Friday (1995)',
 69: 'From Dusk Till Dawn (1996)',
 70: 'Fair Game (1995)',
 71: 'Kicking and Screaming (1995)',
 72: 'Misérables, Les (1995)',
 73: 'Bed of Roses (1996)',
 74: 'Big Bully (1996)',
 75: 'Screamers (1995)',
 76: 'Nico Icon (1995)',
 77: 'Crossing Guard, The (1995)',
 78: 'Juror, The (1996)',
 79: 'White Balloon, The (Badkonake Sefid ) (1995)',
 80: "Things to Do in Denver when You're Dead (1995)",
 81: "Antonia's Line (Antonia) (1995)",
 82: 'Once Upon a Time... When We Were Colored (1995)',
 83: 'Last Summer in the Hamptons (1995)',
 84: 'Angels and Insects (1995)',
 85: 'White Squall (1996)',
 86: 'Dunston Checks In (1996)',
 87: 'Black Sheep (1996)',
 88: 'Nick of Time (1995)',
 89: 'Journey of August King, The (1995)',
 90: 'Mary Reilly (1996)',
 91: 'Vampire in Brooklyn (1995)',
 92: 'Beautiful Girls (1996)',
 93: 'Broken Arrow (1996)',
 94: 'In the Bleak Midwinter (1995)',
 95: 'Hate (Haine, La) (1995)',
 96: 'Shopping (1994)',
 97: 'Heidi Fleiss: Hollywood Madam (1995)',
 98: 'City Hall (1996)',
 99: 'Bottle Rocket (1996)',
 100: 'Mr. Wrong (1996)',
 101: 'Unforgettable (1996)',
 102: 'Happy Gilmore (1996)',
 103: 'Bridges of Madison County, The (1995)',
 104: 'Nobody Loves Me (Keiner liebt mich) (1994)',
 105: 'Muppet Treasure Island (1996)',
 106: 'Catwalk (1995)',
 107: 'Headless Body in Topless Bar (1995)',
 108: 'Braveheart (1995)',
 109: 'Taxi Driver (1976)',
 110: 'Rumble in the Bronx (1995)',
 111: 'Before and After (1996)',
 112: "Margaret's Museum (1995)",
 113: 'Happiness Is in the Field (1995)',
 114: 'Anne Frank Remembered (1995)',
 115: "Young Poisoner's Handbook, The (1995)",
 116: 'If Lucy Fell (1996)',
 117: 'Steal Big, Steal Little (1995)',
 118: 'Race the Sun (1996)',
 119: 'Boys of St. Vincent, The (1993)',
 120: 'Boomerang (1992)',
 121: 'Chungking Express (1994)',
 122: "Star Maker, The (Uomo delle stelle, L') (1995)",
 123: 'Flirting With Disaster (1996)',
 124: 'NeverEnding Story III, The (1994)',
 125: 'Silence of the Palace, The (Saimt el Qusur) (1994)',
 126: "Jupiter's Wife (1994)",
 127: 'Pie in the Sky (1995)',
 128: 'Angela (1995)',
 129: 'Frankie Starlight (1995)',
 130: 'Jade (1995)',
 131: 'Nueba Yol (1995)',
 132: 'Sonic Outlaws (1995)',
 133: 'Down Periscope (1996)',
 134: 'From the Journals of Jean Seberg (1995)',
 135: 'Man of the Year (1995)',
 136: 'Neon Bible, The (1995)',
 137: 'Target (1995)',
 138: 'Up Close and Personal (1996)',
 139: 'Birdcage, The (1996)',
 140: 'Shadows (Cienie) (1988)',
 141: 'Gospa (1995)',
 142: 'Brothers McMullen, The (1995)',
 143: 'Bad Boys (1995)',
 144: 'Amazing Panda Adventure, The (1995)',
 145: 'Basketball Diaries, The (1995)',
 146: 'Awfully Big Adventure, An (1995)',
 147: 'Amateur (1994)',
 148: 'Apollo 13 (1995)',
 149: 'Rob Roy (1995)',
 150: 'Addiction, The (1995)',
 151: 'Batman Forever (1995)',
 152: 'Belle de jour (1967)',
 153: 'Beyond Rangoon (1995)',
 154: 'Blue in the Face (1995)',
 155: 'Canadian Bacon (1994)',
 156: 'Casper (1995)',
 157: 'Clockers (1995)',
 158: 'Congo (1995)',
 159: 'Crimson Tide (1995)',
 160: 'Crumb (1994)',
 161: 'Desperado (1995)',
 162: 'Devil in a Blue Dress (1995)',
 163: 'Die Hard: With a Vengeance (1995)',
 164: 'Doom Generation, The (1995)',
 165: 'Feast of July (1995)',
 166: 'First Knight (1995)',
 167: 'Free Willy 2: The Adventure Home (1995)',
 168: 'Hackers (1995)',
 169: 'Jeffrey (1995)',
 170: 'Johnny Mnemonic (1995)',
 171: 'Judge Dredd (1995)',
 172: 'Jury Duty (1995)',
 173: 'Kids (1995)',
 174: 'Living in Oblivion (1995)',
 175: 'Lord of Illusions (1995)',
 176: 'Love & Human Remains (1993)',
 177: 'Mad Love (1995)',
 178: 'Mallrats (1995)',
 179: 'Mighty Morphin Power Rangers: The Movie (1995)',
 180: 'Moonlight and Valentino (1995)',
 181: 'Mute Witness (1994)',
 182: 'Nadja (1994)',
 183: 'Net, The (1995)',
 184: 'Nine Months (1995)',
 185: 'Party Girl (1995)',
 186: 'Prophecy, The (1995)',
 187: 'Reckless (1995)',
 188: 'Safe (1995)',
 189: 'Scarlet Letter, The (1995)',
 190: 'Show, The (1995)',
 191: 'Showgirls (1995)',
 192: 'Smoke (1995)',
 193: 'Something to Talk About (1995)',
 194: 'Species (1995)',
 195: 'Stars Fell on Henrietta, The (1995)',
 196: 'Strange Days (1995)',
 197: 'Umbrellas of Cherbourg, The (Parapluies de Cherbourg, Les) (1964)',
 198: 'Tie That Binds, The (1995)',
 199: 'Three Wishes (1995)',
 200: 'Total Eclipse (1995)',
 201: 'To Wong Foo, Thanks for Everything! Julie Newmar (1995)',
 202: 'Under Siege 2: Dark Territory (1995)',
 203: 'Unstrung Heroes (1995)',
 204: 'Unzipped (1995)',
 205: 'Walk in the Clouds, A (1995)',
 206: 'Waterworld (1995)',
 207: "White Man's Burden (1995)",
 208: 'Wild Bill (1995)',
 209: 'Browning Version, The (1994)',
 210: 'Bushwhacked (1995)',
 211: 'Burnt By the Sun (Utomlyonnye solntsem) (1994)',
 212: 'Before the Rain (Pred dozhdot) (1994)',
 213: 'Before Sunrise (1995)',
 214: 'Billy Madison (1995)',
 215: 'Babysitter, The (1995)',
 216: 'Boys on the Side (1995)',
 217: 'Cure, The (1995)',
 218: 'Castle Freak (1995)',
 219: 'Circle of Friends (1995)',
 220: 'Clerks (1994)',
 221: 'Don Juan DeMarco (1995)',
 222: 'Disclosure (1994)',
 223: 'Dream Man (1995)',
 224: 'Drop Zone (1994)',
 225: 'Destiny Turns on the Radio (1995)',
 226: 'Death and the Maiden (1994)',
 227: 'Dolores Claiborne (1994)',
 228: 'Dumb & Dumber (1994)',
 229: 'Eat Drink Man Woman (1994)',
 230: 'Exotica (1994)',
 231: 'Exit to Eden (1994)',
 232: 'Ed Wood (1994)',
 233: 'French Kiss (1995)',
 234: 'Forget Paris (1995)',
 235: 'Far From Home: The Adventures of Yellow Dog (1995)',
 236: 'Goofy Movie, A (1995)',
 237: 'Hideaway (1995)',
 238: 'Fluke (1995)',
 239: 'Farinelli: il castrato (1994)',
 240: 'Gordy (1995)',
 241: 'Gumby: The Movie (1995)',
 242: 'Glass Shield, The (1994)',
 243: 'Hoop Dreams (1994)',
 244: 'Heavenly Creatures (1994)',
 245: 'Houseguest (1994)',
 246: 'Immortal Beloved (1994)',
 247: 'Heavyweights (1994)',
 248: 'Hunted, The (1995)',
 249: 'I.Q. (1994)',
 250: 'Interview with the Vampire (1994)',
 251: 'Jefferson in Paris (1995)',
 252: 'Jerky Boys, The (1994)',
 253: 'Junior (1994)',
 254: 'Just Cause (1995)',
 255: "Kid in King Arthur's Court, A (1995)",
 256: 'Kiss of Death (1995)',
 257: 'Star Wars: Episode IV - A New Hope (1977)',
 258: 'Little Women (1994)',
 259: 'Little Princess, A (1995)',
 260: 'Ladybird Ladybird (1994)',
 261: "Enfer, L' (1994)",
 262: 'Like Water for Chocolate (Como agua para chocolate) (1992)',
 263: 'Legends of the Fall (1994)',
 264: 'Major Payne (1994)',
 265: 'Little Odessa (1994)',
 266: 'My Crazy Life (Mi vida loca) (1993)',
 267: 'Love Affair (1994)',
 268: 'Losing Isaiah (1995)',
 269: 'Madness of King George, The (1994)',
 270: "Mary Shelley's Frankenstein (1994)",
 271: 'Man of the House (1995)',
 272: 'Mixed Nuts (1994)',
 273: 'Milk Money (1994)',
 274: 'Miracle on 34th Street (1994)',
 275: 'Miami Rhapsody (1995)',
 276: 'My Family (1995)',
 277: 'Murder in the First (1995)',
 278: "Nobody's Fool (1994)",
 279: 'Nell (1994)',
 280: 'New Jersey Drive (1995)',
 281: 'New York Cop (1996)',
 282: 'Beyond Bedlam (1993)',
 283: 'Nemesis 2: Nebula (1995)',
 284: 'Nina Takes a Lover (1994)',
 285: 'Natural Born Killers (1994)',
 286: 'Only You (1994)',
 287: 'Once Were Warriors (1994)',
 288: 'Poison Ivy II (1995)',
 289: 'Outbreak (1995)',
 290: 'Professional, The (a.k.a. Leon: The Professional) (1994)',
 291: 'Perez Family, The (1995)',
 292: "Pyromaniac's Love Story, A (1995)",
 293: 'Pulp Fiction (1994)',
 294: 'Panther (1995)',
 295: 'Pushing Hands (1992)',
 296: 'Priest (1994)',
 297: 'Quiz Show (1994)',
 298: 'Picture Bride (1995)',
 299: 'Queen Margot (La Reine Margot) (1994)',
 300: 'Quick and the Dead, The (1995)',
 301: 'Roommates (1995)',
 302: 'Ready to Wear (Pret-A-Porter) (1994)',
 303: 'Three Colors: Red (1994)',
 304: 'Three Colors: Blue (1993)',
 305: 'Three Colors: White (1994)',
 306: 'Red Firecracker, Green Firecracker (1994)',
 307: 'Rent-a-Kid (1995)',
 308: 'Relative Fear (1994)',
 309: 'Stuart Saves His Family (1995)',
 310: 'Swan Princess, The (1994)',
 311: 'Secret of Roan Inish, The (1994)',
 312: 'Specialist, The (1994)',
 313: 'Stargate (1994)',
 314: 'Santa Clause, The (1994)',
 315: 'Shawshank Redemption, The (1994)',
 316: 'Shallow Grave (1994)',
 317: 'Suture (1993)',
 318: 'Strawberry and Chocolate (Fresa y chocolate) (1993)',
 319: 'Swimming with Sharks (1995)',
 320: 'Sum of Us, The (1994)',
 321: "National Lampoon's Senior Trip (1995)",
 322: 'To Live (Huozhe) (1994)',
 323: 'Tank Girl (1995)',
 324: 'Tales From the Crypt Presents: Demon Knight (1995)',
 325: 'Star Trek: Generations (1994)',
 326: 'Tales from the Hood (1995)',
 327: 'Tom & Viv (1994)',
 328: 'Village of the Damned (1995)',
 329: 'Tommy Boy (1995)',
 330: 'Vanya on 42nd Street (1994)',
 331: 'Underneath, The (1995)',
 332: 'Walking Dead, The (1995)',
 333: "What's Eating Gilbert Grape (1993)",
 334: 'Virtuosity (1995)',
 335: 'While You Were Sleeping (1995)',
 336: 'War, The (1994)',
 337: 'Double Happiness (1994)',
 338: "Muriel's Wedding (1994)",
 339: 'Baby-Sitters Club, The (1995)',
 340: 'Ace Ventura: Pet Detective (1994)',
 341: 'Adventures of Priscilla, Queen of the Desert, The (1994)',
 342: 'Backbeat (1993)',
 343: 'Bitter Moon (1992)',
 344: 'Bullets Over Broadway (1994)',
 345: 'Clear and Present Danger (1994)',
 346: 'Client, The (1994)',
 347: 'Corrina, Corrina (1994)',
 348: 'Crooklyn (1994)',
 349: 'Crow, The (1994)',
 350: 'Cobb (1994)',
 351: 'Flintstones, The (1994)',
 352: 'Forrest Gump (1994)',
 353: 'Four Weddings and a Funeral (1994)',
 354: 'Higher Learning (1995)',
 355: 'I Like It Like That (1994)',
 356: 'I Love Trouble (1994)',
 357: 'It Could Happen to You (1994)',
 358: 'Jungle Book, The (1994)',
 359: 'Wonderful, Horrible Life of Leni Riefenstahl, The (Die Macht der Bilder) (1993)',
 360: 'Lion King, The (1994)',
 361: 'Little Buddha (1993)',
 362: "Wes Craven's New Nightmare (1994)",
 363: 'Mask, The (1994)',
 364: 'Maverick (1994)',
 365: 'Mrs. Parker and the Vicious Circle (1994)',
 366: 'Naked Gun 33 1/3: The Final Insult (1994)',
 367: 'Paper, The (1994)',
 368: 'Reality Bites (1994)',
 369: 'Red Rock West (1992)',
 370: 'Richie Rich (1994)',
 371: 'Safe Passage (1994)',
 372: 'River Wild, The (1994)',
 373: 'Speed (1994)',
 374: 'Speechless (1994)',
 375: 'Timecop (1994)',
 376: 'True Lies (1994)',
 377: 'When a Man Loves a Woman (1994)',
 378: 'Wolf (1994)',
 379: 'Wyatt Earp (1994)',
 380: 'Bad Company (1995)',
 381: 'Man of No Importance, A (1994)',
 382: 'S.F.W. (1994)',
 383: 'Low Down Dirty Shame, A (1994)',
 384: 'Boys Life (1995)',
 385: 'Colonel Chabert, Le (1994)',
 386: 'Faster Pussycat! Kill! Kill! (1965)',
 387: "Jason's Lyric (1994)",
 388: 'Secret Adventures of Tom Thumb, The (1993)',
 389: 'Street Fighter (1994)',
 390: 'Coldblooded (1995)',
 391: 'Desert Winds (1995)',
 392: 'Fall Time (1995)',
 393: 'Fear, The (1995)',
 394: 'Frank and Ollie (1995)',
 395: 'Girl in the Cadillac (1995)',
 396: 'Homage (1995)',
 397: 'Mirage (1995)',
 398: 'Open Season (1996)',
 399: 'Two Crimes (1995)',
 400: 'Brother Minister: The Assassination of Malcolm X (1994)',
 401: 'Highlander III: The Sorcerer (1994)',
 402: 'Federal Hill (1994)',
 403: 'In the Mouth of Madness (1995)',
 404: '8 Seconds (1994)',
 405: 'Above the Rim (1994)',
 406: 'Addams Family Values (1993)',
 407: 'You So Crazy (1994)',
 408: 'Age of Innocence, The (1993)',
 409: 'Airheads (1994)',
 410: 'Air Up There, The (1994)',
 411: 'Another Stakeout (1993)',
 412: 'Bad Girls (1994)',
 413: 'Barcelona (1994)',
 414: 'Being Human (1993)',
 415: 'Beverly Hillbillies, The (1993)',
 416: 'Beverly Hills Cop III (1994)',
 417: 'Black Beauty (1994)',
 418: 'Blink (1994)',
 419: 'Blown Away (1994)',
 420: 'Blue Chips (1994)',
 421: 'Blue Sky (1994)',
 422: 'Body Snatchers (1993)',
 423: 'Boxing Helena (1993)',
 424: 'Bronx Tale, A (1993)',
 425: 'Cabin Boy (1994)',
 426: 'Calendar Girl (1993)',
 427: "Carlito's Way (1993)",
 428: "City Slickers II: The Legend of Curly's Gold (1994)",
 429: 'Clean Slate (1994)',
 430: 'Cliffhanger (1993)',
 431: 'Coneheads (1993)',
 432: 'Color of Night (1994)',
 433: 'Cops and Robbersons (1994)',
 434: 'Cowboy Way, The (1994)',
 435: 'Dangerous Game (1993)',
 436: 'Dave (1993)',
 437: 'Dazed and Confused (1993)',
 438: 'Demolition Man (1993)',
 439: 'Endless Summer 2, The (1994)',
 440: 'Even Cowgirls Get the Blues (1993)',
 441: 'Fatal Instinct (1993)',
 442: 'Farewell My Concubine (1993)',
 443: 'Favor, The (1994)',
 444: 'Fearless (1993)',
 445: 'Fear of a Black Hat (1993)',
 446: 'With Honors (1994)',
 447: 'Flesh and Bone (1993)',
 448: "Widows' Peak (1994)",
 449: 'For Love or Money (1993)',
 450: 'Firm, The (1993)',
 451: 'Free Willy (1993)',
 452: 'Fresh (1994)',
 453: 'Fugitive, The (1993)',
 454: 'Geronimo: An American Legend (1993)',
 455: 'Getaway, The (1994)',
 456: 'Getting Even with Dad (1994)',
 457: 'Go Fish (1994)',
 458: 'Good Man in Africa, A (1994)',
 459: 'Guilty as Sin (1993)',
 460: 'Hard Target (1993)',
 461: 'Heaven & Earth (1993)',
 462: 'Hot Shots! Part Deux (1993)',
 463: 'Live Nude Girls (1995)',
 464: 'Englishman Who Went Up a Hill, But Came Down a Mountain, The (1995)',
 465: 'House of the Spirits, The (1993)',
 466: 'House Party 3 (1994)',
 467: 'Hudsucker Proxy, The (1994)',
 468: "I'll Do Anything (1994)",
 469: 'In the Army Now (1994)',
 470: 'In the Line of Fire (1993)',
 471: 'In the Name of the Father (1993)',
 472: 'Inkwell, The (1994)',
 473: "What's Love Got to Do with It? (1993)",
 474: 'Jimmy Hollywood (1994)',
 475: 'Judgment Night (1993)',
 476: 'Jurassic Park (1993)',
 477: 'Kalifornia (1993)',
 478: 'Killing Zoe (1994)',
 479: 'King of the Hill (1993)',
 480: 'Lassie (1994)',
 481: 'Last Action Hero (1993)',
 482: 'Life with Mikey (1993)',
 483: 'Lightning Jack (1994)',
 484: 'M. Butterfly (1993)',
 485: 'Made in America (1993)',
 486: 'Malice (1993)',
 487: 'Man Without a Face, The (1993)',
 488: 'Manhattan Murder Mystery (1993)',
 489: 'Menace II Society (1993)',
 490: 'Executive Decision (1996)',
 491: 'In the Realm of the Senses (Ai no corrida) (1976)',
 492: 'What Happened Was... (1994)',
 493: 'Much Ado About Nothing (1993)',
 494: 'Mr. Jones (1993)',
 495: 'Mr. Wonderful (1993)',
 496: 'Mrs. Doubtfire (1993)',
 497: 'Naked (1993)',
 498: 'Next Karate Kid, The (1994)',
 499: 'New Age, The (1994)',
 500: 'No Escape (1994)',
 501: 'North (1994)',
 502: 'Orlando (1993)',
 503: 'Perfect World, A (1993)',
 504: 'Philadelphia (1993)',
 505: 'Piano, The (1993)',
 506: 'Poetic Justice (1993)',
 507: 'Program, The (1993)',
 508: "Robert A. Heinlein's The Puppet Masters (1994)",
 509: 'Radioland Murders (1994)',
 510: 'Ref, The (1994)',
 511: 'Remains of the Day, The (1993)',
 512: 'Renaissance Man (1994)',
 513: 'Rising Sun (1993)',
 514: 'Road to Wellville, The (1994)',
 515: 'Robocop 3 (1993)',
 516: 'Robin Hood: Men in Tights (1993)',
 517: 'Romeo Is Bleeding (1993)',
 518: 'Romper Stomper (1992)',
 519: 'Ruby in Paradise (1993)',
 520: 'Rudy (1993)',
 521: 'Saint of Fort Washington, The (1993)',
 522: 'Savage Nights (Nuits fauves, Les) (1992)',
 523: "Schindler's List (1993)",
 524: 'Scout, The (1994)',
 525: 'Searching for Bobby Fischer (1993)',
 526: 'Second Best (1994)',
 527: 'Secret Garden, The (1993)',
 528: 'Serial Mom (1994)',
 529: 'Shadow, The (1994)',
 530: 'Shadowlands (1993)',
 531: 'Short Cuts (1993)',
 532: 'Simple Twist of Fate, A (1994)',
 533: 'Sirens (1994)',
 534: 'Six Degrees of Separation (1993)',
 535: 'Sleepless in Seattle (1993)',
 536: 'Sliver (1993)',
 537: 'Blade Runner (1982)',
 538: 'Son in Law (1993)',
 539: 'So I Married an Axe Murderer (1993)',
 540: 'Striking Distance (1993)',
 541: 'Harlem (1993)',
 542: 'Super Mario Bros. (1993)',
 543: 'Surviving the Game (1994)',
 544: 'Terminal Velocity (1994)',
 545: 'Thirty-Two Short Films About Glenn Gould (1993)',
 546: 'Threesome (1994)',
 547: 'Nightmare Before Christmas, The (1993)',
 548: 'Three Musketeers, The (1993)',
 549: 'Tombstone (1993)',
 550: 'Trial by Jury (1994)',
 551: 'True Romance (1993)',
 552: 'War Room, The (1993)',
 553: 'Mamma Roma (1962)',
 554: 'Pagemaster, The (1994)',
 555: 'Paris, France (1993)',
 556: 'Beans of Egypt, Maine, The (1994)',
 557: 'Killer (Bulletproof Heart) (1994)',
 558: 'Welcome to the Dollhouse (1995)',
 559: 'Germinal (1993)',
 560: 'Chasers (1994)',
 561: 'Cronos (1992)',
 562: 'Naked in New York (1994)',
 563: 'Kika (1993)',
 564: 'Bhaji on the Beach (1993)',
 565: 'Little Big League (1994)',
 566: 'Slingshot, The (Kådisbellan ) (1993)',
 567: 'Wedding Gift, The (1994)',
 568: 'Foreign Student (1994)',
 569: 'Ciao, Professore! (Io speriamo che me la cavo ) (1993)',
 570: 'Spanking the Monkey (1994)',
 571: 'Little Rascals, The (1994)',
 572: 'Fausto (1993)',
 573: 'Andre (1994)',
 574: 'Hour of the Pig, The (1993)',
 575: 'Scorta, La (1993)',
 576: 'Princess Caraboo (1994)',
 577: 'Celluloid Closet, The (1995)',
 578: 'Metisse (Café au Lait) (1993)',
 579: 'Dear Diary (Caro Diario) (1994)',
 580: "I Don't Want to Talk About It (De eso no se habla) (1993)",
 581: 'Brady Bunch Movie, The (1995)',
 582: 'Home Alone (1990)',
 583: 'Ghost (1990)',
 584: 'Aladdin (1992)',
 585: 'Terminator 2: Judgment Day (1991)',
 586: 'Dances with Wolves (1990)',
 587: 'Tough and Deadly (1995)',
 588: 'Batman (1989)',
 589: 'Silence of the Lambs, The (1991)',
 590: 'Snow White and the Seven Dwarfs (1937)',
 591: 'Beauty and the Beast (1991)',
 592: 'Pinocchio (1940)',
 593: 'Pretty Woman (1990)',
 594: 'Window to Paris (1994)',
 595: 'Wild Bunch, The (1969)',
 596: 'Love and a .45 (1994)',
 597: "Wooden Man's Bride, The (Wu Kui) (1994)",
 598: 'Great Day in Harlem, A (1994)',
 599: 'Bye Bye, Love (1995)',
 600: 'Criminals (1996)',

In [205]:
import pickle
import os

# Create data output directory
os.makedirs("data", exist_ok=True)

# Align User Metadata DataFrame to mapped user_id indices (0..6039)
user_meta_df = users.sort_values('user_id')[['gender', 'age', 'occupation']].reset_index(drop=True)

# 1. Package all essentials into a dictionary
preprocessed_artifacts = {
    # Data DataFrames / Arrays
    'train_ratings': train_ratings[['user_id', 'item_id', 'target']], # Training split DataFrame
    'test_ratings': test_ratings[['user_id', 'item_id', 'target']],   # Test split DataFrame
    'user_meta_df': user_meta_df,                                     # Demographic feature table
    'item_genre_matrix': genre_matrix,                           # Multi-hot genre array (3706, 18)
    
    # Metadata Mappings & Counts
    'idx_to_user' : idx_to_user,
    'idx_to_item' : idx_to_item,
    'idx_to_title': idx_to_title,
    'user_to_idx': user_to_idx,
    'item_to_idx': item_to_idx,
    'num_users': num_users,                                           # 6040
    'num_items': num_items,                                           # 3706
    'num_genres': num_genres                                           # 18
}

# 2. Save artifact file to disk
with open("data/movielens_preprocessed.pkl", "wb") as f:
    pickle.dump(preprocessed_artifacts, f)

print("Preprocessed essentials successfully saved to data/movielens_preprocessed.pkl!")

Preprocessed essentials successfully saved to data/movielens_preprocessed.pkl!